version: '2'
services:
  elastic:
    build: elasticsearch
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - ES_JAVA_OPTS=-Xms500m -Xmx500m
  apache:
    build: apache
    ports:
      - "443:443"
    volumes:
      - ./logs:/usr/local/apache2/logs
