FROM elasticsearch:5.3
# WARNING elasticsearch image is DEPRECATED and will stop being updated from
# 2017-06-20. See https://hub.docker.com/_/elasticsearch/

ADD elasticdna.dump.tar /
ADD config /usr/share/elasticsearch/config
